#Material names can be found here:
#https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
#
#CaSe SeNsItIvE
disabled_items:
  - HOPPER
  - TNT
#Use this to disable all recipes
disable_all: false
#Whether or not you want the plugin to
#Tell you when there is an update available
check_for_updates: true
#Do not change
config_version: 4