name: NoCraftPlus
main: net.corruptmc.nocraftplus.NoCraftPlugin
version: 2.0.1
api-version: 1.13
commands:
  nocraftplus:
    description: Base command.
    aliases: [ncp]
permissions:
  nocraftplus.*:
    children:
      nocraftplus.bypass.*: true
      nocraftplus.command: true
      nocraftplus.command.add: true
      nocraftplus.command.help: true
      nocraftplus.command.list: true
      nocraftplus.command.reload: true
      nocraftplus.command.remove: true
      nocraftplus.updatecheck: true
  nocraftplus.bypass.*:
    description: Bypass all item filters.
  nocraftplus.bypass.<item>:
    description: Bypass specific item filter.
  nocraftplus.command:
    description: Access to command.
  nocraftplus.command.add:
    description: Add an item filter.
  nocraftplus.command.help:
    description: Get help.
  nocraftplus.command.list:
    description: List current item filters.
  nocraftplus.command.reload:
    description: Reload item filters from config.
  nocraftplus.command.remove:
    description: Remove an item filter.
  nocraftplus.updatecheck:
    description: Alert when update is available.